### ISSUE TITLE
ERROR -- : RedisActor: CLEANUP CRASHED! IOError: selector is closed

### ISSUE THREAD

**Issue by ggayan** [celluloid/celluloid-redis#11]
Celluloid-io crashes when killing an app using pub/sub with celluloid-redis on MRI v2.0.0-p247. JRuby 1.7.4 runs fine.

I've setup an example here: https://gist.github.com/ggayan/6126358
The app throws a segfault with nio4r v0.4.6

Cheers

**Comment by tarcieri** [comment]
This is a known bug and fixed on nio4r master, however you will still get
an exception

On Jul 31, 2013, at 2:35 PM, Gabriel Gayan Fanta notifications@github.com
wrote:

Celluloid-io crashes when killing an app using pub/sub with celluloid-redis
on MRI v2.0.0-p247. JRuby 1.7.4 runs fine.

I've setup an example here: https://gist.github.com/ggayan/6126358
The app throws a segfault with nio4r v0.4.6

Cheers

—
Reply to this email directly or view it on
GitHubhttps://github.com/celluloid/celluloid-redis/issues/11
.

## 

Tony Arcieri

On Jul 31, 2013, at 2:35 PM, Gabriel Gayan Fanta notifications@github.com
wrote:

Celluloid-io crashes when killing an app using pub/sub with celluloid-redis
on MRI v2.0.0-p247. JRuby 1.7.4 runs fine.

I've setup an example here: https://gist.github.com/ggayan/6126358
The app throws a segfault with nio4r v0.4.6

Cheers

—
Reply to this email directly or view it on
GitHubhttps://github.com/celluloid/celluloid-redis/issues/11
.

**Comment by ggayan** [comment]
Yup, It's the exception that I was reporting. Is it a problem with how pub/sub is implemented in the redis gem? why does JRuby shuts down cleanly?

**Comment by tarcieri** [comment]
Not sure yet. The nio4r bug has been fixed. There seems to be another bug
though

## 

Tony Arcieri

On Jul 31, 2013, at 3:34 PM, Gabriel Gayan Fanta notifications@github.com
wrote:

Yup, It's the exception that I was reporting. Is it a problem with how
pub/sub is implemented in the redis gem?

—
Reply to this email directly or view it on
GitHubhttps://github.com/celluloid/celluloid-redis/issues/11#issuecomment-21901309
.

**Comment by ggayan** [comment]
Do I raise an issue in nio4r or something?

Cheers

**Comment by tarcieri** [comment]
This probably isn't nio4r related at this point. It's probably a bug in celluloid-redis or celluloid-io /cc @halorgium

**Comment by bmxpert1** [comment]
Is there a current way to get around this issue on MRI? It's not hurting anything really, just kind of annoying... 
Thanks

**Comment by tarcieri** [comment]
It looks like the culprit is here:

```
/Users/tonyarcieri/.rvm/gems/ruby-2.0.0-p247/gems/redis-3.0.6/lib/redis/subscribe.rb:20:in `unsubscribe'
```

redis-rb is trying to unsubscribe after the selector has been shut down, and this is trying to open a new connection to Redis, which tries to use the selector to wait for the connection to complete.

So this is a sort of ordering bug. Unsubscribe needs to happen prior to the selector being shut down.

**Comment by robertjpayne** [comment]
They use a monitor ( so same thread can re-enter ) around all of the redis commands. Then the subscribe command enters a endless loop waiting for published messages or a connection error.

We're pretty much stuffed here, and I'm completely shocked at this implementation in redis-rb as it makes it impossible to do anything with the client from a second thread unless you're willing to forcefully kill the thread.

**Comment by robertjpayne** [comment]
The solution is to get rid of redis-rb's horrific synchronization. Luckily if you keep the redis client inside of single Celluloid actor you're going to be thread safe and monkey patching out the synchronization is a cake walk.

Then there is patching up a few things so that the unsubscribe call never hits the connection ( since it's disconnected and gone anyway seriously.

Here is an example, I tried to subclass where possible and minimise the monkey patch madness so hopefully future redis-rb revisions don't explode.

https://gist.github.com/robertjpayne/8171587

The more I look at this and how simple redis-rb is it may make more sense to completely fork the redis-rb repo and make it better for celluloid anyways.

**Comment by robertjpayne** [comment]
Or better yet it may be best to simply patch the MONITOR and PUB/SUB commands they are all horrendously locked/synchronised.

The MONITOR command is actually 100% impossible to get out of without killing the thread/process.
